-- Add issueGroupId to conversations
ALTER TABLE "conversations_conversation" 
ADD COLUMN "issue_group_id" bigint;
--> statement-breakpoint

-- Create issue_groups table for manual management
CREATE TABLE "issue_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"mailbox_id" bigint NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint

-- Add pinned issue groups to user profiles as JSON array
ALTER TABLE "user_profiles" 
ADD COLUMN "pinned_issue_group_ids" jsonb DEFAULT '[]'::jsonb;
--> statement-breakpoint

-- Create indexes for performance
CREATE INDEX "conversations_issue_group_id_idx" ON "conversations_conversation" ("issue_group_id");
--> statement-breakpoint
CREATE INDEX "issue_groups_mailbox_id_idx" ON "issue_groups" ("mailbox_id");
--> statement-breakpoint
CREATE INDEX "issue_groups_created_at_idx" ON "issue_groups" ("created_at");
--> statement-breakpoint

-- Enable RLS for security
ALTER TABLE "issue_groups" ENABLE ROW LEVEL SECURITY;