CREATE TABLE "conversation_issue_groups" (
	"conversation_id" bigint NOT NULL,
	"issue_group_id" bigint NOT NULL,
	CONSTRAINT "conversation_issue_groups_conversation_id_issue_group_id_pk" PRIMARY KEY("conversation_id","issue_group_id")
);
--> statement-breakpoint
ALTER TABLE "conversation_issue_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "issue_groups" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "issue_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text,
	"embedding" vector(1536)
);
--> statement-breakpoint
ALTER TABLE "issue_groups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "conversation_issue_groups_conversation_id_idx" ON "conversation_issue_groups" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversation_issue_groups_issue_group_id_idx" ON "conversation_issue_groups" USING btree ("issue_group_id");--> statement-breakpoint
CREATE INDEX "issue_groups_created_at_idx" ON "issue_groups" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "issue_groups_embedding_idx" ON "issue_groups" USING hnsw ("embedding" vector_cosine_ops);