CREATE TABLE "user_pinned_issue_groups" (
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_pinned_issue_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"issue_group_id" bigint NOT NULL,
	CONSTRAINT "user_pinned_issue_groups_user_id_issue_group_id_key" UNIQUE("user_id","issue_group_id")
);
--> statement-breakpoint
ALTER TABLE "user_pinned_issue_groups" ENABLE ROW LEVEL SECURITY;