CREATE TABLE IF NOT EXISTS "conversation_agent_read_status" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation_agent_read_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"conversation_id" bigint NOT NULL,
	"agent_clerk_id" text NOT NULL,
	"last_read_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_agent_read_status_conversation_id_idx" ON "conversation_agent_read_status" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_agent_read_status_agent_clerk_id_idx" ON "conversation_agent_read_status" USING btree ("agent_clerk_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_agent_read_status_conversation_agent_idx" ON "conversation_agent_read_status" USING btree ("conversation_id","agent_clerk_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "conversation_agent_read_status_conversation_agent_unique" ON "conversation_agent_read_status" USING btree ("conversation_id","agent_clerk_id");--> statement-breakpoint
ALTER TABLE "conversation_agent_read_status" ENABLE ROW LEVEL SECURITY;